### ISSUE TITLE
List dependencies/requirements

### ISSUE THREAD

**Issue by DanielLenz** [mirapy-org/tutorials#6]
It would be great to have the actual requirements in the `environment.yml`, or in an equivalent file. This is also part of the JOSS requirements (https://github.com/openjournals/joss-reviews/issues/1557)

**Comment by swapsha96** [comment]
I have created `requirements.txt` file in this repo. I hope this resolves this issue.

**Comment by DanielLenz** [comment]
Thanks! I think there a few dependencies missing (mirapy itself, opencv, sklearn, etc.). Could you make sure the requirement are complete?

**Comment by swapsha96** [comment]
Initially, I thought visitors won't be needing all the packages since tutorials have different requirements so they will be installing accordingly. But you are correct and I have added all of them. I should have been careful with all the requirements.
